# This workflow will run our tests, generate an lcov code coverage file,
# and send that coverage to Coveralls 

name: Code Coverage

on:
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  Coveralls:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: git config --global user.email "slapshot@yext.com"
    - run: git config --global user.name "Jambo run-tests.yml"
    - run: npx jest --config=jest-coverage.json
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}